spring.application.name=api-gateway
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
server.port=8765
spring.cloud.config.enabled=false

# Route to book-service
spring.cloud.gateway.server.webmvc.routes[0].id=book-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://bookstore-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/books/**

# Route to order-service
spring.cloud.gateway.server.webmvc.routes[1].id=order-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://order-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/orders/**

# Route to user-service
spring.cloud.gateway.server.webmvc.routes[2].id=user-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://user-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/users/**